SkillUp/force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SkillUp/force-app/main/default/objects/Trainee__c/Trainee__c.object-meta.xml
<CustomObject>
    <label>Trainee</label>
    <nameField>
        <label>Trainee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SkillUp/force-app/main/default/objects/Trainee__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Trainees</relationshipLabel>
    <relationshipName>Trainees</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

SkillUp/force-app/main/default/objects/Trainer__c/Trainer__c.object-meta.xml
<CustomObject>
    <label>Trainer</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Trainer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SkillUp/force-app/main/default/classes/certificateerorController.cls
public class certificateerorController {
    
    public Trainee__c traineelist {get;set;}
    public Course__c courselist {get;set;}
    public certificateerorController() {
        traineelist=[SELECT Name,Completion_Date__c,Course__c  FROM Trainee__c where Id=:ApexPages.currentPage().getParameters().get('id') LIMIT 1000];
        courselist=[Select Name,Trainer__c from Course__c Where id=:traineelist.Course__c LIMIT 1000];
       
        
    }
  }