SkillUp/force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SkillUp/force-app/main/default/objects/Trainee__c/Trainee__c.object-meta.xml
<CustomObject>
    <label>Trainee</label>
    <nameField>
        <label>Trainee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SkillUp/force-app/main/default/objects/Trainee__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Trainees</relationshipLabel>
    <relationshipName>Trainees</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

SkillUp/force-app/main/default/objects/Trainer__c/Trainer__c.object-meta.xml
<CustomObject>
    <label>Trainer</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Trainer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SkillUp/force-app/main/default/objects/Trainer__c/fields/Trainer_Name__c.field-meta.xml
<CustomField>
    <fullName>Trainer_Name__c</fullName>
    <label>Trainer Name</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

SkillUp/force-app/main/default/classes/certificateComponentController.cls
public class certificateComponentController {    
    public String recordId {get;set;}
    public String traineeName {get;set;}
    public String courseName {get;set;}
    public String trainerName {get;set;}
    public Date completionDate {get;set;}
    public List<Trainee__c> traineeList {get;set;}
    Set<Id> commonSet {get;set;}
    public List<Course__c> courselist {get;set;}
    public List<Trainer__c> trainerlist {get;set;}
    public certificateComponentController() {
       getData();
    }
    //getData() Retrieve the data required for the certificate component from Trainee , Course and Trainer objects.
    public List<sObject> getData(){
        commonSet = New Set<Id>();
        
        //Getting the Trainee Id from the Trainee Detail page and setting it to recordId variable
        recordId = ApexPages.currentPage().getParameters().get('id');
        system.debug('record id '+recordId);
         if(String.isNotEmpty(recordId))
         {
             traineeList = [SELECT Name,Completion_Date__c,Course__c  FROM Trainee__c where Id=:recordId LIMIT 1];
        	 for( Trainee__c traineeObj : traineeList )
        	 {
                   if(traineeObj.Course__c != Null) 
                       commonSet.add(traineeObj.Course__c);
            	   traineeName = traineeObj.Name;
            	   completionDate = traineeObj.Completion_Date__c;
             }
        	 courselist=[Select Name,Trainer__c from Course__c Where Id IN: commonSet LIMIT 1];
        	 for( Course__c courseObj : courselist )
             {
                   if(courseObj.Trainer__c != Null) 
                       commonSet.add(courseObj.Trainer__c);
            	   courseName = courseObj.Name;
            
             }
             trainerlist=[Select Trainer_Name__c from Trainer__c where Id IN: commonSet LIMIT 1];
             for( Trainer__c trainerObj : trainerlist )
             {
            	trainerName = trainerObj.Trainer_Name__c ;
        	 }
             System.debug('new trainee list '+traineeList);
             return traineeList;
         }
        
        else
        {
            return new List<Trainee__c>();
        }
    }
  }