SkillUp/force-app/main/default/objects/Account/fields/Last_Month_Dues__c.field-meta.xml
<CustomField>
    <fullName>Last_Month_Dues__c</fullName>
    <inlineHelpText>This field contains the total course fees of all the employees of the company enrolled in Skill Up training.</inlineHelpText>
    <label>Last Month Dues</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

SkillUp/force-app/main/default/objects/Trainee__c/Trainee__c.object-meta.xml
<CustomObject>
    <label>Trainee</label>
    <nameField>
        <label>Trainee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SkillUp/force-app/main/default/objects/Trainee__c/fields/Corporation__c.field-meta.xml
<CustomField>
    <fullName>Corporation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corporation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Trainees</relationshipLabel>
    <relationshipName>Trainees</relationshipName>
    <type>Lookup</type>
</CustomField>

SkillUp/force-app/main/default/classes/AccountDue.cls
global class AccountDue implements Database.Batchable<sobject>
{
	List<AggregateResult> trainee_AggList = new List<AggregateResult>();
    Set<Id> commonSet= new Set<Id>();
    
    global Database.QueryLocator start(Database.BatchableContext BC) 
    {
        return Database.getQueryLocator([
            SELECT 
                Id,Last_Month_Dues__c,
                (SELECT Id, Name FROM Contacts WHERE Primary__c=true)
            FROM
                Account
            WHERE
                Id
            IN
                (SELECT AccountId FROM Contact WHERE Primary__c=true)]);
    }
    
    global void execute(Database.BatchableContext BC, List<Account> scope) 
    {
        System.debug('scope -- '+ scope);
        
        for(Account accountobj : scope)
        {
                if(accountobj.Id !=null)
                  commonSet.add(accountobj.Id);
        }
        trainee_AggList = [Select Corporation__c,Sum(Course_fee__c) Total_Due 
                                                 from Trainee__c where Corporation__c in : commonSet
                                                 Group By Corporation__c ];
        System.debug('Aggregated Result: '+trainee_AggList);
        List<Account> listofAccountsToUpdate = new List<Account>(); 
        if (trainee_AggList.size()>0)
        {
            for(AggregateResult aggResult : trainee_AggList)
            {
                	Account acc = new Account();
                	acc.Id = (String) aggResult.get('Corporation__c');
                	acc.Last_Month_Dues__c = (Double) aggResult.get('Total_Due');
                    listofAccountsToUpdate.add(acc);
            }
        }
        
		System.debug('List Of Updated Accounts ' + listofAccountsToUpdate);
        update listofAccountsToUpdate;
    }
    global void finish(Database.BatchableContext BC) 
    {
        system.debug('Common Set value in finish method: '+ commonSet);
        List<Contact> listOfContacts = [SELECT Id, Name, Email, Account.Last_Month_Dues__c,Account.Name, AccountId FROM Contact 
                                        WHERE Primary__c=true ];
        
        List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
        
        for(Contact con : listOfContacts ) 
        {	
			Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
			List<String> sendTo = new List<String>();
			sendTo.add(con.Email);
			mail.setToAddresses(sendTo);
			mail.setSenderDisplayName('Team SkillUp');
			mail.setSubject('Account Last Month Due !!!');
            String body = 'Hello ' + con.Name + ',' + '<br>' +
                ' This mail is to provide the information related to '+ con.Account.Name +' Last Month Due.'
                + 'Your this month due is ' + con.Account.Last_Month_Dues__c +'<br><br>'+ 
                'Thanks & Regards' + '<br><br>'+'Team SkillUp';
            mail.setHtmlBody(body);
            mails.add(mail);
    	}
        Messaging.sendEmail(mails);

	}
}